# Generated by Django 4.2.23 on 2025-06-25 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва бренду')),
                ('slug', models.SlugField(blank=True, max_length=70, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'бренд',
                'verbose_name_plural': 'Бренди',
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'категорію',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('main_image', models.ImageField(blank=True, default='products/default.jpg', upload_to='products/', verbose_name='Головне зображення')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ціна')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Знижка у %')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість')),
                ('is_new', models.BooleanField(default=False, help_text='Позначити як новий товар', verbose_name='Товар новий?')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='goods.brands', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='goods.categories', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Мотоцикл',
                'verbose_name_plural': 'Мотоцикли',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gearbox_type', models.CharField(choices=[('механічна', 'Механічна'), ('автоматична', 'Автоматична'), ('CVT', 'CVT')], max_length=20, verbose_name='Тип КПП')),
                ('gears_count', models.IntegerField(verbose_name='Кількість передач')),
                ('gearbox_description', models.CharField(help_text='Наприклад: послідовна (схема 1-0-2-3-4-5)', max_length=200, verbose_name='Опис КПП')),
                ('drive_type', models.CharField(choices=[('ланцюговий', 'Ланцюговий'), ('ременевий', 'Ременевий'), ('кардановий', 'Кардановий')], max_length=20, verbose_name='Тип приводу')),
                ('clutch_description', models.CharField(help_text='Наприклад: механічне, багатодискове, в масляній ванні', max_length=200, verbose_name='Зчеплення')),
                ('motorcycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transmission', to='goods.motorcycle', verbose_name='Мотоцикл')),
            ],
            options={
                'verbose_name': 'Трансмісія',
                'verbose_name_plural': 'Трансмісії',
            },
        ),
        migrations.CreateModel(
            name='PerformanceSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_speed', models.IntegerField(verbose_name='Максимальна швидкість (км/год)')),
                ('fuel_tank_volume', models.FloatField(verbose_name="Об'єм паливного бака (л)")),
                ('fuel_consumption', models.FloatField(verbose_name='Витрати палива (л/100км)')),
                ('curb_weight', models.IntegerField(verbose_name='Вага споряджена (кг)')),
                ('seat_height', models.IntegerField(verbose_name='Висота по сидінню (мм)')),
                ('length', models.IntegerField(verbose_name='Довжина (мм)')),
                ('width', models.IntegerField(verbose_name='Ширина (мм)')),
                ('height', models.IntegerField(verbose_name='Висота (мм)')),
                ('warranty_months', models.IntegerField(verbose_name='Гарантія (місяців)')),
                ('load_capacity', models.IntegerField(verbose_name='Вантажопідйомність (кг)')),
                ('country_of_origin', models.CharField(max_length=100, verbose_name='Країна виробництва')),
                ('motorcycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='goods.motorcycle', verbose_name='Мотоцикл')),
            ],
            options={
                'verbose_name': 'Експлуатаційні характеристики',
                'verbose_name_plural': 'Експлуатаційні характеристики',
            },
        ),
        migrations.CreateModel(
            name='MotorcycleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='motorcycles/', verbose_name='Зображення')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Назва зображення')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основне зображення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.motorcycle', verbose_name='Мотоцикл')),
            ],
            options={
                'verbose_name': 'Зображення мотоцикла',
                'verbose_name_plural': 'Зображення мотоциклів',
                'ordering': ['-is_main', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(help_text='Наприклад: бензиновий, 4-х тактний, FT163FML', max_length=100, verbose_name='Тип двигуна')),
                ('cylinder_description', models.CharField(help_text='Наприклад: 1-циліндровий, з верхнім розташуванням розподільного валу SOHC', max_length=200, verbose_name='Опис циліндрів')),
                ('max_power_hp', models.FloatField(verbose_name='Максимальна потужність (к.с.)')),
                ('max_power_rpm', models.IntegerField(verbose_name='Обороти при макс. потужності (об./хв.)')),
                ('torque_nm', models.FloatField(verbose_name='Обертаючий момент (Нм)')),
                ('torque_rpm', models.IntegerField(verbose_name='Обороти при макс. моменті (об./хв.)')),
                ('displacement', models.IntegerField(verbose_name="Об'єм двигуна (см³)")),
                ('cooling', models.CharField(choices=[('повітряне', 'Повітряне'), ('рідинне', 'Рідинне'), ('комбіноване', 'Комбіноване')], max_length=20, verbose_name='Охолодження двигуна')),
                ('start_type', models.CharField(help_text='Наприклад: електростартер [з ключа/кнопки] та механічний стартер', max_length=200, verbose_name='Тип запуску')),
                ('balance_shaft', models.BooleanField(default=False, verbose_name='Балансувальний вал')),
                ('fuel_system', models.CharField(choices=[('карбюраторна', 'Карбюраторна'), ('інжекторна', 'Інжекторна')], max_length=20, verbose_name='Система упорскування палива')),
                ('motorcycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engine', to='goods.motorcycle', verbose_name='Мотоцикл')),
            ],
            options={
                'verbose_name': 'Двигун',
                'verbose_name_plural': 'Двигуни',
            },
        ),
        migrations.CreateModel(
            name='ChassisAndBrakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_brake_type', models.CharField(choices=[('дисковий', 'Дисковий'), ('барабанний', 'Барабанний')], max_length=20, verbose_name='Тип переднього гальма')),
                ('rear_brake_type', models.CharField(choices=[('дисковий', 'Дисковий'), ('барабанний', 'Барабанний')], max_length=20, verbose_name='Тип заднього гальма')),
                ('front_brake_description', models.CharField(help_text='Наприклад: дисковий, гідравлічний', max_length=200, verbose_name='Опис переднього гальма')),
                ('rear_brake_description', models.CharField(help_text='Наприклад: дисковий, гідравлічний', max_length=200, verbose_name='Опис заднього гальма')),
                ('front_suspension', models.CharField(choices=[('телескопічна вилка', 'Телескопічна вилка'), ('маятникова', 'Маятникова'), ('моноаморт', 'Моноаморт')], max_length=50, verbose_name='Передня підвіска')),
                ('rear_suspension', models.CharField(help_text='Наприклад: маятникова, два амортизатори', max_length=200, verbose_name='Задня підвіска')),
                ('front_wheel', models.CharField(help_text='Розмір у форматі 90/90-17 R', max_length=50, verbose_name='Переднє колесо')),
                ('rear_wheel', models.CharField(help_text='Розмір у форматі 120/80-17 R', max_length=50, verbose_name='Заднє колесо')),
                ('wheelbase', models.IntegerField(verbose_name='Колісна база (мм)')),
                ('ground_clearance', models.IntegerField(verbose_name='Дорожній просвіт (мм)')),
                ('motorcycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chassis', to='goods.motorcycle', verbose_name='Мотоцикл')),
            ],
            options={
                'verbose_name': 'Ходова частина і гальма',
                'verbose_name_plural': 'Ходова частина і гальма',
            },
        ),
        migrations.CreateModel(
            name='AdditionalFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_description', models.TextField(help_text='Опис приладової панелі та її функцій', verbose_name='Приладова панель')),
                ('lighting_description', models.TextField(help_text='Опис системи освітлення', verbose_name='Світло')),
                ('lubrication_system', models.CharField(help_text='Наприклад: тиском та розбризкуванням, з мокрим картером', max_length=200, verbose_name='Система змазки')),
                ('recommended_oil', models.TextField(help_text='Рекомендації по моторній оливі', verbose_name='Рекомендована олія')),
                ('motorcycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='goods.motorcycle', verbose_name='Мотоцикл')),
            ],
            options={
                'verbose_name': 'Додаткові характеристики',
                'verbose_name_plural': 'Додаткові характеристики',
            },
        ),
        migrations.AddIndex(
            model_name='motorcycle',
            index=models.Index(fields=['category', 'brand'], name='goods_motor_categor_69364c_idx'),
        ),
    ]
