# Generated by Django 4.2.23 on 2025-06-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorcycle',
            name='main_image',
        ),
    ]
