# Generated by Django 4.2.23 on 2025-06-12 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва бренду')),
                ('slug', models.SlugField(blank=True, max_length=70, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'бренд',
                'verbose_name_plural': 'Бренди',
                'db_table': 'brand',
            },
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'категорію', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('main_image', models.ImageField(blank=True, default='products/default.jpg', upload_to='products/', verbose_name='Головне зображення')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ціна')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Знижка у %')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='goods.brands', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='goods.categories', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'Продукти',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='CategoryBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='goods.brands', verbose_name='Бренд')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='goods.categories', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'категорію-бренд',
                'verbose_name_plural': 'Категорії-бренди',
                'db_table': 'category_brand',
            },
        ),
    ]
