# Generated by Django 4.2.23 on 2025-06-12 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_brands_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorybrand',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='categorybrand',
            old_name='category_id',
            new_name='category',
        ),
    ]
