# Generated by Django 4.2.23 on 2025-06-28 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_motorcycle_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва кольору')),
                ('hex_code', models.CharField(blank=True, help_text='Наприклад: #FF0000', max_length=7, null=True, verbose_name='HEX код')),
            ],
            options={
                'verbose_name': 'Колір',
                'verbose_name_plural': 'Кольори',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MotorcycleVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0.0, help_text="Додаткова вартість за цей колір (може бути від'ємною)", max_digits=10, verbose_name='Модифікатор ціни')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість на складі')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступний для замовлення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.color', verbose_name='Колір')),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='goods.motorcycle', verbose_name='Мотоцикл')),
            ],
            options={
                'verbose_name': 'Варіант мотоцикла',
                'verbose_name_plural': 'Варіанти мотоциклів',
                'ordering': ['motorcycle', 'color'],
                'unique_together': {('motorcycle', 'color')},
            },
        ),
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='motorcycle_variants/', verbose_name='Зображення')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Назва зображення')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основне зображення')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортування')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.motorcyclevariant', verbose_name='Варіант')),
            ],
            options={
                'verbose_name': 'Зображення варіанту',
                'verbose_name_plural': 'Зображення варіантів',
                'ordering': ['sort_order', '-is_main', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='MotorcycleImage',
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='colors',
            field=models.ManyToManyField(through='goods.MotorcycleVariant', to='goods.color', verbose_name='Доступні кольори'),
        ),
    ]
