# Generated by Django 4.2.23 on 2025-07-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_breaksystem_color_motorcyclevariant_suspensionsystem_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
    ]
