# Generated by Django 4.2.23 on 2025-07-01 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_color_motorcyclevariant_variantimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_brake_type', models.CharField(choices=[('дисковий', 'Дисковий'), ('барабанний', 'Барабанний')], max_length=20, verbose_name='Тип переднього гальма')),
                ('rear_brake_type', models.CharField(choices=[('дисковий', 'Дисковий'), ('барабанний', 'Барабанний')], max_length=20, verbose_name='Тип заднього гальма')),
                ('front_brake_description', models.CharField(help_text='Наприклад: дисковий, гідравлічний', max_length=200, verbose_name='Опис переднього гальма')),
                ('rear_brake_description', models.CharField(help_text='Наприклад: дисковий, гідравлічний', max_length=200, verbose_name='Опис заднього гальма')),
                ('motorcycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brakes', to='goods.motorcycle', verbose_name='Мотоцикл')),
            ],
            options={
                'verbose_name': 'гальма',
                'verbose_name_plural': 'гальма',
            },
        ),
        migrations.CreateModel(
            name='SuspensionSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_suspension', models.CharField(choices=[('телескопічна вилка', 'Телескопічна вилка'), ('маятникова', 'Маятникова'), ('моноаморт', 'Моноаморт')], max_length=50, verbose_name='Передня підвіска')),
                ('rear_suspension', models.CharField(help_text='Наприклад: маятникова, два амортизатори', max_length=200, verbose_name='Задня підвіска')),
                ('front_wheel', models.CharField(help_text='Розмір у форматі 90/90-17 R', max_length=50, verbose_name='Переднє колесо')),
                ('rear_wheel', models.CharField(help_text='Розмір у форматі 120/80-17 R', max_length=50, verbose_name='Заднє колесо')),
                ('wheelbase', models.IntegerField(verbose_name='Колісна база (мм)')),
                ('ground_clearance', models.IntegerField(verbose_name='Дорожній просвіт (мм)')),
                ('motorcycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chassis', to='goods.motorcycle', verbose_name='Мотоцикл')),
            ],
            options={
                'verbose_name': 'Ходова частина',
                'verbose_name_plural': 'Ходові частини',
            },
        ),
        migrations.DeleteModel(
            name='ChassisAndBrakes',
        ),
    ]
