# Generated by Django 4.2.23 on 2025-07-01 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_rename_brands_brand_rename_categories_category_and_more'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='goods.motorcyclevariant', verbose_name='Варіант (колір)'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Ключ сесії'),
        ),
    ]
