# Generated by Django 4.2.23 on 2025-06-25 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Текст на голонвій')),
            ],
            options={
                'verbose_name': 'головна сторінка',
                'verbose_name_plural': 'головні сторінки',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='slides', verbose_name='зображення слайду')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='опис до зображення')),
                ('alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='що на картинці? ')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='позиція слайду')),
                ('main_page', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='slides', to='main.mainpage', verbose_name='Головна сторінка')),
            ],
            options={
                'verbose_name': 'слайд',
                'verbose_name_plural': 'слайди',
                'ordering': ['order'],
            },
        ),
    ]
