# Generated by Django 4.2.23 on 2025-07-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='alt',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='що на картинці? '),
        ),
        migrations.AlterField(
            model_name='slide',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='опис до зображення'),
        ),
    ]
